name: aijokes
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  responsive_framework: ^1.4.0
  get: ^4.6.1
  flutter_mobx: ^2.2.0+2
  freezed_annotation: ^2.4.1
  google_fonts: ^6.2.0
  http: ^1.2.1
  auto_route: ^7.8.4
  go_router: ^13.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  mobx_codegen: ^2.6.0+1
  json_serializable: ^6.7.1
  freezed: ^2.4.7


flutter:
  uses-material-design: true
